### ISSUE TITLE
Seeing below error when start stratum pool, any idea why it happened?

### ISSUE THREAD

**Issue by myaleon** [UlordChain/ulord-node-stratum-pool#1]
Seeing below error when start stratum pool, any idea why it happened?
Thanks.

root@ubuntu-16:/var/tmp/ulord-node-stratum-pool# npm start

> ulord-pool@0.1.0 start /var/tmp/ulord-node-stratum-pool
> node init.js

2018-04-25 15:04:04 [POSIX]     [Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2018-04-25 15:04:04 [Master]    [CLI] CLI listening on port 17117
2018-04-25 15:04:04 [PPLNT]     [ulord] TimeShare processing setup with redis (127.0.0.1:6379)
2018-04-25 15:04:05 [Payments]  [ulord]  minimum paymentInterval of 120 seconds recommended.
2018-04-25 15:04:05 [Payments]  [ulord] ulord requireShielding: false
2018-04-25 15:04:05 [Payments]  [ulord] ulord minConf: 10
2018-04-25 15:04:05 [Payments]  [ulord] ulord payments txfee reserve: 0.000005
2018-04-25 15:04:05 [Payments]  [ulord] ulord maxBlocksPerPayment: 50
2018-04-25 15:04:05 [Payments]  [ulord] ulord PPLNT: true, time period: 0.51
2018-04-25 15:04:05 [Payments]  [ulord] Payment processing setup with daemon (ulordpool@127.0.0.1:9889) and redis (127.0.0.1:6379)
2018-04-25 15:04:05 [Master]    [PoolSpawner] Spawned 1 pool(s) on 1 thread(s)
null
null
2018-04-25 15:04:05 [Website]   [Server] Website started on 0.0.0.0:8080
2018-04-25 15:04:05 [Switching] [Setup] (Thread 1) Loading last proxy state from redis
null
2018-04-25 15:04:05 [Pool]      [ulord] (Thread 1) Share processing setup with redis (127.0.0.1:6379)
null
2018-04-25 15:04:06 [Pool]      [ulord] (Thread 1) Daemon is still syncing with network (download blockchain) - server will be started once synced
2018-04-25 15:04:06 [Pool]      [ulord] (Thread 1) Downloaded 13.12% of blockchain from 5 peers
2018-04-25 15:04:11 [Pool]      [ulord] (Thread 1) Downloaded 13.12% of blockchain from 5 peers
2018-04-25 15:04:16 [Pool]      [ulord] (Thread 1) Downloaded 13.12% of blockchain from 5 peers
2018-04-25 15:04:21 [Pool]      [ulord] (Thread 1) Downloaded 13.12% of blockchain from 5 peers
2018-04-25 15:04:26 [Pool]      [ulord] (Thread 1) Downloaded 13.12% of blockchain from 5 peers
2018-04-25 15:04:31 [Pool]      [ulord] (Thread 1) Downloaded 13.12% of blockchain from 5 peers
2018-04-25 15:04:36 [Pool]      [ulord] (Thread 1) Downloaded 13.12% of blockchain from 5 peers
2018-04-25 15:04:41 [Pool]      [ulord] (Thread 1) Downloaded 13.12% of blockchain from 5 peers
2018-04-25 15:04:46 [Pool]      [ulord] (Thread 1) Downloaded 13.12% of blockchain from 5 peers
2018-04-25 15:04:51 [Pool]      [ulord] (Thread 1) Downloaded 13.12% of blockchain from 5 peers
2018-04-25 15:04:56 [Pool]      [ulord] (Thread 1) Downloaded 13.12% of blockchain from 5 peers
buffer.js:152
      throw new Error(
      ^

Error: If encoding is specified then the first argument must be a string
    at new Buffer (buffer.js:152:13)
    at Object.exports.uint256BufferFromHash (/var/tmp/ulord-node-stratum-pool/node_modules/stratum-pool/lib/util.js:63:19)
    at Object.exports.createGeneration (/var/tmp/ulord-node-stratum-pool/node_modules/stratum-pool/lib/transactions.js:168:14)
    at new BlockTemplate (/var/tmp/ulord-node-stratum-pool/node_modules/stratum-pool/lib/blockTemplate.js:55:33)
    at JobManager.processTemplate (/var/tmp/ulord-node-stratum-pool/node_modules/stratum-pool/lib/jobManager.js:140:32)
    at /var/tmp/ulord-node-stratum-pool/node_modules/stratum-pool/lib/pool.js:615:62
    at itemFinished (/var/tmp/ulord-node-stratum-pool/node_modules/stratum-pool/lib/daemon.js:163:36)
    at /var/tmp/ulord-node-stratum-pool/node_modules/stratum-pool/lib/daemon.js:176:17
    at parseJson (/var/tmp/ulord-node-stratum-pool/node_modules/stratum-pool/lib/daemon.js:91:17)
    at IncomingMessage.<anonymous> (/var/tmp/ulord-node-stratum-pool/node_modules/stratum-pool/lib/daemon.js:101:17)
2018-04-25 15:05:01 [Master]    [PoolSpawner] Fork 0 died, spawning replacement worker...
2018-04-25 15:05:03 [Switching] [Setup] (Thread 1) Loading last proxy state from redis
2018-04-25 15:05:03 [Pool]      [ulord] (Thread 1) Share processing setup with redis (127.0.0.1:6379)

**Comment by taylorshuang** [comment]
Which version of nodejs  are you use?

**Comment by ZyanWlayor** [comment]
The cause of this problem may be that the nodejs version is too high.  
You can switch to v4.8.7 by installing n modules like this:
$npm i n -g
$n 4.8.7

**Comment by myaleon** [comment]
This is the version for nodejs:
root@ubuntu-16:/var/tmp/ulord-node-stratum-pool# node -v
v8.11.1

**Comment by taylorshuang** [comment]
You need use nodejs v4.8.7，using nvm use 4.8.7

**Comment by ZyanWlayor** [comment]
We use the old version of nodejs because some algorithm modules are compiled under 4.8.7, and you have to switch to version 4.8.7. @myaleon
