### ISSUE TITLE
遇到一个异常

### ISSUE THREAD

**Issue by lynnnnnnnn** [UlordChain/ulord-node-stratum-pool#23]
2018-05-22 21:52:49 [Master]    [PoolSpawner] Fork 0 died, spawning replacement worker...
null
buffer.js:74
      throw new Error(
      ^

Error: If encoding is specified then the first argument must be a string
    at new Buffer (buffer.js:74:13)
    at Object.exports.uint256BufferFromHash (/root/ulord-node-stratum-pool/node_modules/stratum-pool/lib/util.js:63:19)
    at Object.exports.createGeneration (/root/ulord-node-stratum-pool/node_modules/stratum-pool/lib/transactions.js:140:14)
    at new BlockTemplate (/root/ulord-node-stratum-pool/node_modules/stratum-pool/lib/blockTemplate.js:55:33)
    at JobManager.processTemplate (/root/ulord-node-stratum-pool/node_modules/stratum-pool/lib/jobManager.js:140:32)
    at /root/ulord-node-stratum-pool/node_modules/stratum-pool/lib/pool.js:618:62
    at itemFinished (/root/ulord-node-stratum-pool/node_modules/stratum-pool/lib/daemon.js:162:36)
    at /root/ulord-node-stratum-pool/node_modules/stratum-pool/lib/daemon.js:175:17
    at parseJson (/root/ulord-node-stratum-pool/node_modules/stratum-pool/lib/daemon.js:91:17)
    at IncomingMessage.<anonymous> (/root/ulord-node-stratum-pool/node_modules/stratum-pool/lib/daemon.js:101:17)
2018-05-22 21:52:50 [Master]    [PoolSpawner] Fork 1 died, spawning replacement worker...

**Comment by lynnnnnnnn** [comment]
已解决，是nodejs 版本太高了
