### ISSUE TITLE
what is the reason of this error? thx

### ISSUE THREAD

**Issue by yangwb** [UlordChain/ulord-node-stratum-pool#56]
when I run "npm start" command, there are some errors:
 root@ubuntu:~/ulord-node-stratum-pool# npm start

> ulord-pool@0.1.0 start /root/ulord-node-stratum-pool
> node init.js

fs.js:1236
    throw error;
    ^

Error: watch /root/ulord-node-stratum-pool/web/ulordrig.exe ENOENT
    at exports._errnoException (util.js:907:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at Object.<anonymous> (/root/ulord-node-stratum-pool/libs/apiEx.js:33:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

npm ERR! Linux 4.4.0-128-generic
npm ERR! argv "/root/.nvm/versions/node/v4.8.7/bin/node" "/root/.nvm/versions/node/v4.8.7/bin/npm" "start"
npm ERR! node v4.8.7
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! ulord-pool@0.1.0 start: `node init.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ulord-pool@0.1.0 start script 'node init.js'.
npm ERR! This is most likely a problem with the ulord-pool package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node init.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ulord-pool
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls ulord-pool
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/ulord-node-stratum-pool/npm-debug.log

what is the reason? 
Thanks

**Comment by ZyanWlayor** [comment]
I'm sorry.This file is used to verify the miner MD5.I fixed it.Please download the newest code.

**Comment by yangwb** [comment]
Thank you very much.
I just use the command: git clone https://github.com/UlordChain/ulord-node-stratum-pool.git ulord-node-stratum-pool 
to get the code, isn't it the newest one? I am not so familiar with the git, How can I get the newest code?
Thank you very much!




086-186-1198-2760




在2018年08月17 16时55分, "Zyan Wlayor"<notifications@github.com>写道:



I'm sorry.This file is used to verify the miner MD5.I fixed it.Please download the newest code.

**Comment by yangwb** [comment]
I have used the "git pull" command updated the local code.
but the errors comes again, like that:


root@ubuntu:~/ulord-node-stratum-pool# npm start


> ulord-pool@0.1.0 start /root/ulord-node-stratum-pool
> node init.js


2018-08-17 08:23:43 [POSIX][Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2018-08-17 08:23:43 [Master][ulord_example.json] Pool has same configured coin file coins/ulord.json as ulord.json pool


npm ERR! Linux 4.4.0-128-generic
npm ERR! argv "/root/.nvm/versions/node/v4.8.7/bin/node" "/root/.nvm/versions/node/v4.8.7/bin/npm" "start"
npm ERR! node v4.8.7
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! ulord-pool@0.1.0 start: `node init.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ulord-pool@0.1.0 start script 'node init.js'.
npm ERR! This is most likely a problem with the ulord-pool package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node init.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ulord-pool
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls ulord-pool
npm ERR! There is likely additional logging output above.


npm ERR! Please include the following file with any support request:
npm ERR!     /root/ulord-node-stratum-pool/npm-debug.log


could you please tell me the reason?
Thank you very much!




086-186-1198-2760




在2018年08月17 16时55分, "Zyan Wlayor"<notifications@github.com>写道:



I'm sorry.This file is used to verify the miner MD5.I fixed it.Please download the newest code.

**Comment by ZyanWlayor** [comment]
Emm,it maybe ulord_example.json and ulord.json has the same configurations.You can delect one of them.A same port can't appear in config files.

**Comment by aymoon05** [comment]
Install node-pre-gyp will fix your issue

$ apt install node-pre-gyp
