### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by yangwb** [UlordChain/ulord-node-stratum-pool#57]
Thank you for your help very much!
I have can run the pool now, but when I access the website, It shows "数据尚未同步", why?
Thank you.

**Comment by taylorshuang** [comment]
Is Ulord daemon running?

**Comment by taylorshuang** [comment]
Please run 'ps aux|grep ulord' and screen shot here.

**Comment by yangwb** [comment]
Thank for your help！


the screen shot is:


yang@yang-ubuntu:~/ulord-node-stratum-pool/pool_configs$ ps aux|grep ulord
yang      3061  0.0  0.0  28788  3244 pts/12   S+   10:13   0:00 screen -R ulord
yang      3062  0.0  0.0  29064  2888 ?        Ss   10:13   0:00 SCREEN -R ulord
yang      3235 98.8  1.6 1260416 66664 pts/5   SLl  10:14  13:07 ./ulordd
yang      3794  0.4  3.1 1013236 127608 pts/5  Sl+  10:18   0:02 /home/yang/.nvm/versions/node/v4.8.7/bin/node /home/yang/ulord-node-stratum-pool/init.js
yang      3816  0.4  3.1 1013236 127512 pts/5  Sl+  10:18   0:02 /home/yang/.nvm/versions/node/v4.8.7/bin/node /home/yang/ulord-node-stratum-pool/init.js
yang      3822  0.4  3.1 1013236 127280 pts/5  Sl+  10:18   0:02 /home/yang/.nvm/versions/node/v4.8.7/bin/node /home/yang/ulord-node-stratum-pool/init.js
yang      3828  0.4  3.1 1013236 127144 pts/5  Sl+  10:18   0:02 /home/yang/.nvm/versions/node/v4.8.7/bin/node /home/yang/ulord-node-stratum-pool/init.js
yang      3834  0.4  3.1 1012328 126868 pts/5  Sl+  10:18   0:02 /home/yang/.nvm/versions/node/v4.8.7/bin/node /home/yang/ulord-node-stratum-pool/init.js
yang      3973  6.8  3.1 1013348 126476 pts/5  Sl+  10:27   0:02 /home/yang/.nvm/versions/node/v4.8.7/bin/node /home/yang/ulord-node-stratum-pool/init.js
yang      3987  0.0  0.0  15960  1016 pts/21   S+   10:27   0:00 grep --color=auto ulord




and the website console shows something like this:






TypeError: Cannot read property 'networkDiff' of null
    at Multi.callback (/home/yang/ulord-node-stratum-pool/libs/statsEx.js:136:46)
    at multi_callback (/home/yang/ulord-node-stratum-pool/node_modules/redis/lib/multi.js:89:14)
    at Command.callback (/home/yang/ulord-node-stratum-pool/node_modules/redis/lib/multi.js:116:9)
    at normal_reply (/home/yang/ulord-node-stratum-pool/node_modules/redis/index.js:726:21)
    at RedisClient.return_reply (/home/yang/ulord-node-stratum-pool/node_modules/redis/index.js:824:9)
    at JavascriptRedisParser.Parser.returnReply (/home/yang/ulord-node-stratum-pool/node_modules/redis/index.js:192:18)
    at JavascriptRedisParser.execute (/home/yang/ulord-node-stratum-pool/node_modules/redis/node_modules/redis-parser/lib/parser.js:574:12)
    at Socket.<anonymous> (/home/yang/ulord-node-stratum-pool/node_modules/redis/index.js:274:27)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
2018-08-18 10:28:10 [Master]    [Website] Website process died, spawning replacement...
2018-08-18 10:28:13 [Website]   [Server] Website thread started on 0.0.0.0:8080
2018-08-18 10:28:13 [Website]   [Historics] reversed history!
2018-08-18 10:28:25 [Payments]  [ulord] Unauthorized RPC access - invalid RPC username or password
/home/yang/ulord-node-stratum-pool/libs/statsEx.js:136
                                _this.cacheStats.networkDiff = replies[1].networkDiff;
                                                                         ^


TypeError: Cannot read property 'networkDiff' of null
    at Multi.callback (/home/yang/ulord-node-stratum-pool/libs/statsEx.js:136:46)
    at multi_callback (/home/yang/ulord-node-stratum-pool/node_modules/redis/lib/multi.js:89:14)
    at Command.callback (/home/yang/ulord-node-stratum-pool/node_modules/redis/lib/multi.js:116:9)
    at normal_reply (/home/yang/ulord-node-stratum-pool/node_modules/redis/index.js:726:21)
    at RedisClient.return_reply (/home/yang/ulord-node-stratum-pool/node_modules/redis/index.js:824:9)
    at JavascriptRedisParser.Parser.returnReply (/home/yang/ulord-node-stratum-pool/node_modules/redis/index.js:192:18)
    at JavascriptRedisParser.execute (/home/yang/ulord-node-stratum-pool/node_modules/redis/node_modules/redis-parser/lib/parser.js:574:12)
    at Socket.<anonymous> (/home/yang/ulord-node-stratum-pool/node_modules/redis/index.js:274:27)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
2018-08-18 10:29:13 [Master]    [Website] Website process died, spawning replacement...
2018-08-18 10:29:16 [Website]   [Server] Website thread started on 0.0.0.0:8080
2018-08-18 10:29:16 [Website]   [Historics] reversed history!
2018-08-18 10:29:23 [Payments]  [ulord] Unauthorized RPC access - invalid RPC username or password


谢谢你！






086-186-1198-2760




在2018年08月18 09时37分, "taylorshuang"<notifications@github.com>写道:



Please run 'ps aux|grep ulord' and screen shot here.

**Comment by yangwb** [comment]
Hi,


There is another question： if I use a cloud server to run ulord pool, what is the appropriate configuration? for example: the cpu, the memory,the bandwidth and the disk.


Thank you very much!




杨文彬  


086-186-1198-2760




在2018年08月18 09时37分, "taylorshuang"<notifications@github.com>写道:



Please run 'ps aux|grep ulord' and screen shot here.
