### ISSUE TITLE
Cannot read property 'foundpayee' of undefined

### ISSUE THREAD

**Issue by zheng9980419** [UlordChain/ulord-node-stratum-pool#6]
root@pjyt:/home/pool/ulord-node-stratum-pool# node init.js
2018-05-17 13:43:41 [POSIX]     [Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2018-05-17 13:43:41 [Master]    [CLI] CLI listening on port 17117
2018-05-17 13:43:41 [PPLNT]     [bitblockscoin] TimeShare processing setup with redis (127.0.0.1:6379)
null
2018-05-17 13:43:42 [Payments]  [bitblockscoin]  minimum paymentInterval of 120 seconds recommended.
2018-05-17 13:43:42 [Payments]  [bitblockscoin] bitblockscoin requireShielding: false
2018-05-17 13:43:42 [Payments]  [bitblockscoin] bitblockscoin minConf: 10
2018-05-17 13:43:42 [Payments]  [bitblockscoin] bitblockscoin payments txfee reserve: 0.000005
2018-05-17 13:43:42 [Payments]  [bitblockscoin] bitblockscoin maxBlocksPerPayment: 50
2018-05-17 13:43:42 [Payments]  [bitblockscoin] bitblockscoin PPLNT: true, time period: 0.51
2018-05-17 13:43:42 [Payments]  [bitblockscoin] Payment processing setup with daemon (teste@127.0.0.1:9988) and redis (127.0.0.1:6379)
2018-05-17 13:43:42 [Website]   [Server] Website started on 0.0.0.0:8080
2018-05-17 13:43:42 [Master]    [PoolSpawner] Spawned 1 pool(s) on 4 thread(s)
2018-05-17 13:43:42 [Switching] [Setup] (Thread 1) Loading last proxy state from redis
2018-05-17 13:43:42 [Pool]      [bitblockscoin] (Thread 1) Share processing setup with redis (127.0.0.1:6379)
2018-05-17 13:43:42 [Switching] [Setup] (Thread 1) Last proxy state loaded from redis
null
null
2018-05-17 13:43:43 [Switching] [Setup] (Thread 2) Loading last proxy state from redis
2018-05-17 13:43:43 [Pool]      [bitblockscoin] (Thread 2) Share processing setup with redis (127.0.0.1:6379)
2018-05-17 13:43:43 [Switching] [Setup] (Thread 2) Last proxy state loaded from redis
2018-05-17 13:43:43 [Switching] [Setup] (Thread 3) Loading last proxy state from redis
2018-05-17 13:43:43 [Pool]      [bitblockscoin] (Thread 3) Share processing setup with redis (127.0.0.1:6379)
2018-05-17 13:43:43 [Switching] [Setup] (Thread 3) Last proxy state loaded from redis
null
2018-05-17 13:43:43 [Switching] [Setup] (Thread 4) Loading last proxy state from redis
2018-05-17 13:43:43 [Pool]      [bitblockscoin] (Thread 4) Share processing setup with redis (127.0.0.1:6379)
2018-05-17 13:43:43 [Switching] [Setup] (Thread 4) Last proxy state loaded from redis
/home/pool/ulord-node-stratum-pool/node_modules/stratum-pool/lib/transactions.js:19
    if (rpcData.Foundnode.foundpayee) {
                         ^

TypeError: Cannot read property 'foundpayee' of undefined
    at generateOutputTransactions (/home/pool/ulord-node-stratum-pool/node_modules/stratum-pool/lib/transactions.js:19:26)
    at Object.exports.createGeneration (/home/pool/ulord-node-stratum-pool/node_modules/stratum-pool/lib/transactions.js:152:30)
    at new BlockTemplate (/home/pool/ulord-node-stratum-pool/node_modules/stratum-pool/lib/blockTemplate.js:55:33)
    at JobManager.processTemplate (/home/pool/ulord-node-stratum-pool/node_modules/stratum-pool/lib/jobManager.js:140:32)
    at /home/pool/ulord-node-stratum-pool/node_modules/stratum-pool/lib/pool.js:615:62
    at itemFinished (/home/pool/ulord-node-stratum-pool/node_modules/stratum-pool/lib/daemon.js:162:36)
    at /home/pool/ulord-node-stratum-pool/node_modules/stratum-pool/lib/daemon.js:175:17
    at parseJson (/home/pool/ulord-node-stratum-pool/node_modules/stratum-pool/lib/daemon.js:91:17)
    at IncomingMessage.<anonymous> (/home/pool/ulord-node-stratum-pool/node_modules/stratum-pool/lib/daemon.js:101:17)
    at emitNone (events.js:72:20)
2018-05-17 13:43:43 [Master]    [PoolSpawner] Fork 0 died, spawning replacement worker...
null
null
/home/pool/ulord-node-stratum-pool/node_modules/stratum-pool/lib/transactions.js:19
    if (rpcData.Foundnode.foundpayee) {
                         ^

TypeError: Cannot read property 'foundpayee' of undefined
    at generateOutputTransactions (/home/pool/ulord-node-stratum-pool/node_modules/stratum-pool/lib/transactions.js:19:26)
    at Object.exports.createGeneration (/home/pool/ulord-node-stratum-pool/node_modules/stratum-pool/lib/transactions.js:152:30)
    at new BlockTemplate (/home/pool/ulord-node-stratum-pool/node_modules/stratum-pool/lib/blockTemplate.js:55:33)
    at JobManager.processTemplate (/home/pool/ulord-node-stratum-pool/node_modules/stratum-pool/lib/jobManager.js:140:32)
    at /home/pool/ulord-node-stratum-pool/node_modules/stratum-pool/lib/pool.js:615:62
    at itemFinished (/home/pool/ulord-node-stratum-pool/node_modules/stratum-pool/lib/daemon.js:162:36)
    at /home/pool/ulord-node-stratum-pool/node_modules/stratum-pool/lib/daemon.js:175:17
    at parseJson (/home/pool/ulord-node-stratum-pool/node_modules/stratum-pool/lib/daemon.js:91:17)
    at IncomingMessage.<anonymous> (/home/pool/ulord-node-stratum-pool/node_modules/stratum-pool/lib/daemon.js:101:17)
    at emitNone (events.js:72:20)
2018-05-17 13:43:44 [Master]    [PoolSpawner] Fork 1 died, spawning replacement worker...

**Comment by let5sne** [comment]
@zheng9980419 你的node 版本是多少 执行了npm install 么

**Comment by zheng9980419** [comment]
node 4.9.1
npm update  
没有执行npm install

**Comment by zheng9980419** [comment]
@let5sne  你的node 是什么版本 我是scrypt算法的币 跟这个有关系么？

**Comment by let5sne** [comment]
@zheng9980419 

npm install installs all modules that are listed on package.json file and their dependencies.

npm update updates all packages in the node_modules directory and their dependencies.

scrypt 没试过呢

**Comment by ZyanWlayor** [comment]
We are not familiar with bitblockscoin's structure, and it seems that we do not support its RPC service.

**Comment by let5sne** [comment]
@zheng9980419 今天测试其它coin 遇到相同的问题 解决办法 请将 package.json 中的
"stratum-pool": "git+https://github.com/UlordChain/node-stratum-pool.git" 替换为 "stratum-pool": "^0.1.6" 试试
